### PR TITLE
Add debug check to continueResolution

### PR DESCRIPTION
**Pull request by malaire**
Adding this debug check makes Example 5bis fail earlier, and also makes Examples 3 and 4 fail.

The code in `Ok () ->` branch has not been changed, just indented, but GitHub diff isn't good enough to show this.

### CODE REVIEW

**Comment by harrysarson** [comment]
GitHub is actually good enough, but only when you tell it to be:

https://github.com/mpizenberg/elm-pubgrub/pull/2/files?diff=split&w=1

(Check the whitespace box to get github working)
image

**Comment by malaire** [comment]
That hides the lines completely. There is no option to see the lines, but have the changed parts highlighted, which would only highlight whitespace here.

**Comment by harrysarson** [comment]
Aha very true, maybe if you click the button really fast and also blink lots the two will merge! Anyway I am only being nosy here. The change looks good to me though :)

**Comment by malaire** [comment]
Not related to PubGrub, but I'm currently working on an Elm package which is about diffing, so I'm taking notes of how other algorithms handle different situations.

Still has some issues like long lines.

combined-diff

**Comment by mpizenberg** [comment]
I've just had a look at the PR code now. I don't think the added check is correct but let me know if you think I'm wrong. You're adding a check to verify that `priorCause` almost satisfies the partial solution inside continue resolution whereas this relation is only supposed to be verified if the complete conflict resolution step ended (cf https://github.com/dart-lang/pub/blob/master/doc/solver.md#unit-propagation).

I believe this is my fault because while refactoring some of the code I kept the comment "priorCause is guaranted to be almost satisfied by the partial solution" at that location whereas that comment should only appear at the end of conflict resolution (line 244).

I think I've refactored that main `PubGrub.elm` algorithm module a 1000 times to convert the very procedural (with mutations) description of the algorithm into a functional recursive one. That's also why there are less doc comments here than in the other modules.

**Comment by malaire** [comment]
Yes I think you are right. I added that check because of your comment, and I didn't check the Pubgrub algorithm as I don't quite understand conflict resolution yet. But re-reading that part now, there is no mention of priorCause almost satisfying inside the algorithm.

**Pull request closed without merging**
